/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Robot;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;


/**
 *
 * @author engeer
 */
public class levelFailedWindow extends javax.swing.JFrame {
    JTabbedPane jTabbedPane1;
    JPanel difficultyPanel;
    JPanel startPanel;
    JButton playButton;
    /**
     * Creates new form quitOrRestartWindow
     */
    public levelFailedWindow() {
        initComponents();
    }
    public levelFailedWindow(JTabbedPane jTabbedPane1, JPanel difficultyPanel, JButton playButton, JPanel startPanel){
        initComponents();
        this.jTabbedPane1 =jTabbedPane1;
        this.difficultyPanel =difficultyPanel;
        this.playButton =playButton;
        this.startPanel =startPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restartButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        restartButton.setText("Restart");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(restartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 62, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/promptWindow.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_restartButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.setSelectedComponent(startPanel);
        playButton.setVisible(true);
        difficultyPanel.setVisible(false);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        int centerX = screenSize.width/2;
//        int centerY = screenSize.height/2;
//        
//         try {
//            // These coordinates are screen coordinates
//            int xCoord = centerX;
//            int yCoord = centerY;
//
//            // Move the cursor
//            Robot robot = new Robot();
//            robot.mouseMove(xCoord, yCoord);
//          } catch (AWTException e) {
//              System.out.println(e);
//          }
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton restartButton;
    // End of variables declaration//GEN-END:variables
}
