/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;
import java.net.URL;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JButton;
/**
 *
 * @author engeer
 */
public class mainFrame extends javax.swing.JFrame {
    
    Timer timer =new Timer();
    Timer timer1 =new Timer();
    
    private int clickCounter=1;//--
    boolean firstClick=true,notDone=false,notDone2=false; 
    int j,i,x,y, b, sumAS;
    int x1 = 50,x2 = 50,y1 = 50,y2 = 50;
    //
    int cardInstances = 2;
    int cardInstances1 = 3;
    int cardInstances2 = 6;
    
    //
    public int[][] cardArrayH = new int[2][2];
    public int[][] cardArrayS = new int[2][2];
    
    public int[][] cardArrayH1 = new int[3][2];
    public int[][] cardArrayS1 ={ { 1, 1 }, { 1, 1}, { 1, 1 } };
    
    public int[][] cardArrayH2 = new int[3][4];
    public int[][] cardArrayS2 ={ { 1, 1,1, 1 }, { 1, 1, 1, 1}, { 1, 1, 1, 1 } };
    
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        gamePanel1 = new javax.swing.JPanel();
        jButtonEasy00 = new javax.swing.JButton();
        jButtonEasy01 = new javax.swing.JButton();
        jButtonEasy10 = new javax.swing.JButton();
        jButtonEasy11 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        gamePanel2 = new javax.swing.JPanel();
        jButtonEasyy00 = new javax.swing.JButton();
        jButtonEasyy01 = new javax.swing.JButton();
        jButtonEasyy20 = new javax.swing.JButton();
        jButtonEasyy10 = new javax.swing.JButton();
        jButtonEasyy11 = new javax.swing.JButton();
        jButtonEasyy21 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        gamePanel3 = new javax.swing.JPanel();
        jButtonMedium00 = new javax.swing.JButton();
        jButtonMedium10 = new javax.swing.JButton();
        jButtonMedium01 = new javax.swing.JButton();
        jButtonMedium11 = new javax.swing.JButton();
        jButtonMedium21 = new javax.swing.JButton();
        jButtonMedium20 = new javax.swing.JButton();
        jButtonMedium02 = new javax.swing.JButton();
        jButtonMedium12 = new javax.swing.JButton();
        jButtonMedium22 = new javax.swing.JButton();
        jButtonMedium03 = new javax.swing.JButton();
        jButtonMedium13 = new javax.swing.JButton();
        jButtonMedium23 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        gamePanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(153, 0, 255));

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(548, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(27, 27, 27))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 627));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(210, 240, 240));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        gamePanel1.setBackground(new java.awt.Color(240, 210, 240));
        gamePanel1.setEnabled(false);

        jButtonEasy00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonEasy00.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEasy00.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonEasy00.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonEasy00.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonEasy00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEasy00ActionPerformed(evt);
            }
        });

        jButtonEasy01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonEasy01.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEasy01.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonEasy01.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonEasy01.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonEasy01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEasy01ActionPerformed(evt);
            }
        });

        jButtonEasy10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonEasy10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEasy10.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonEasy10.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonEasy10.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonEasy10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEasy10ActionPerformed(evt);
            }
        });

        jButtonEasy11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonEasy11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEasy11.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonEasy11.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonEasy11.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonEasy11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEasy11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePanel1Layout = new javax.swing.GroupLayout(gamePanel1);
        gamePanel1.setLayout(gamePanel1Layout);
        gamePanel1Layout.setHorizontalGroup(
            gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(gamePanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEasy10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEasy11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gamePanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEasy00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEasy01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        gamePanel1Layout.setVerticalGroup(
            gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEasy01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEasy00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEasy11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEasy10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", gamePanel1);

        jPanel6.setBackground(new java.awt.Color(240, 210, 230));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        gamePanel2.setBackground(new java.awt.Color(40, 240, 240));

        jButtonEasyy00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonEasyy00.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEasyy00.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy00.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy00.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonEasyy00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEasyy00ActionPerformed(evt);
            }
        });

        jButtonEasyy01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonEasyy01.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEasyy01.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy01.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy01.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonEasyy01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEasyy01ActionPerformed(evt);
            }
        });

        jButtonEasyy20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonEasyy20.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEasyy20.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy20.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy20.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonEasyy20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEasyy20ActionPerformed(evt);
            }
        });

        jButtonEasyy10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonEasyy10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEasyy10.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy10.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy10.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonEasyy10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEasyy10ActionPerformed(evt);
            }
        });

        jButtonEasyy11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonEasyy11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEasyy11.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy11.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy11.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonEasyy11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEasyy11ActionPerformed(evt);
            }
        });

        jButtonEasyy21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonEasyy21.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEasyy21.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy21.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonEasyy21.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonEasyy21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEasyy21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePanel2Layout = new javax.swing.GroupLayout(gamePanel2);
        gamePanel2.setLayout(gamePanel2Layout);
        gamePanel2Layout.setHorizontalGroup(
            gamePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel2Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(gamePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePanel2Layout.createSequentialGroup()
                        .addComponent(jButtonEasyy20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEasyy21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gamePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(gamePanel2Layout.createSequentialGroup()
                            .addComponent(jButtonEasyy10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonEasyy11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(gamePanel2Layout.createSequentialGroup()
                            .addComponent(jButtonEasyy00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonEasyy01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        gamePanel2Layout.setVerticalGroup(
            gamePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanel2Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(gamePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEasyy01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEasyy00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gamePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEasyy11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEasyy10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gamePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEasyy20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEasyy21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
        );

        jTabbedPane1.addTab("tab5", gamePanel2);

        jPanel8.setBackground(new java.awt.Color(240, 40, 240));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanel8);

        gamePanel3.setBackground(new java.awt.Color(240, 240, 40));

        jButtonMedium00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium00.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium00.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium00.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium00.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium00ActionPerformed(evt);
            }
        });

        jButtonMedium10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium10.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium10.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium10.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium10ActionPerformed(evt);
            }
        });

        jButtonMedium01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium01.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium01.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium01.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium01.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium01ActionPerformed(evt);
            }
        });

        jButtonMedium11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium11.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium11.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium11.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium11ActionPerformed(evt);
            }
        });

        jButtonMedium21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium21.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium21.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium21.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium21.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium21ActionPerformed(evt);
            }
        });

        jButtonMedium20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium20.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium20.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium20.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium20.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium20ActionPerformed(evt);
            }
        });

        jButtonMedium02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium02.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium02.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium02.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium02.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium02ActionPerformed(evt);
            }
        });

        jButtonMedium12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium12.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium12.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium12.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium12ActionPerformed(evt);
            }
        });

        jButtonMedium22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium22.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium22.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium22.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium22.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium22ActionPerformed(evt);
            }
        });

        jButtonMedium03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium03.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium03.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium03.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium03.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium03ActionPerformed(evt);
            }
        });

        jButtonMedium13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium13.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium13.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium13.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium13ActionPerformed(evt);
            }
        });

        jButtonMedium23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium23.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium23.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium23.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium23.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePanel3Layout = new javax.swing.GroupLayout(gamePanel3);
        gamePanel3.setLayout(gamePanel3Layout);
        gamePanel3Layout.setHorizontalGroup(
            gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanel3Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePanel3Layout.createSequentialGroup()
                        .addComponent(jButtonMedium20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(gamePanel3Layout.createSequentialGroup()
                            .addComponent(jButtonMedium10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonMedium11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(gamePanel3Layout.createSequentialGroup()
                            .addComponent(jButtonMedium00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonMedium01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMedium22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonMedium12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonMedium02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMedium23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonMedium13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonMedium03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );
        gamePanel3Layout.setVerticalGroup(
            gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanel3Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePanel3Layout.createSequentialGroup()
                        .addComponent(jButtonMedium03, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gamePanel3Layout.createSequentialGroup()
                        .addComponent(jButtonMedium02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gamePanel3Layout.createSequentialGroup()
                        .addGroup(gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonMedium01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMedium00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonMedium11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMedium10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMedium20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMedium21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(141, 141, 141))
        );

        jTabbedPane1.addTab("tab7", gamePanel3);

        jPanel10.setBackground(new java.awt.Color(20, 240, 20));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab8", jPanel10);

        javax.swing.GroupLayout gamePanel4Layout = new javax.swing.GroupLayout(gamePanel4);
        gamePanel4.setLayout(gamePanel4Layout);
        gamePanel4Layout.setHorizontalGroup(
            gamePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        gamePanel4Layout.setVerticalGroup(
            gamePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab9", gamePanel4);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab10", jPanel12);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, -23, -1, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEasy00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEasy00ActionPerformed
        // TODO add your handling code here:
        // @here
        if(firstClick){
            firstClickRandomizer();
            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS[0][0]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==0 && y1==0){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;
            
            b =cardArrayH[0][0];     //***
            buttonImageGiver(jButtonEasy00, b);
            x1=0;                                 //***
            y1=0;                                 //***
            System.out.println("1st choice");
        }else{
            
            notDone2= true;
            
            
            b =cardArrayH[0][0];     //***
            buttonImageGiver(jButtonEasy00, b);
            x2=0;                                 //*** 
            y2=0;                                 //***  
            System.out.println("2nd choice");
                
            ArrayHCompare();
            sumArrayS();             
            clickCounter=1;
            }
        
    }//GEN-LAST:event_jButtonEasy00ActionPerformed

    public void sumArrayS(){ //checks the array value to know how many left to pair and if the game ends
        sumAS=0;
        for(i = 0; i<cardInstances; i++)
            {
                for(j = 0; j<cardInstances; j++)
                    {
                        sumAS+=cardArrayS[i][j];
                    }
            }
         System.out.println("Cards to match: "+ sumAS);
         if(sumAS==0){
                System.out.println("Congrats! Game Completed");
                imageClear();
                firstClick = true;
//                System.out.println("total time: "+min+"min. and "+sec%60+" sec.");
//                task.cancel(); // not cancel but reset timers only

                
            }
         
    }
    public void sumArrayS1(){ //checks the array value to know how many left to pair and if the game ends
        sumAS=0;
//        for(i = 0; i<cardInstances; i++)
//            {
//                for(j = 0; j<cardInstances; j++)
//                    {
//                        sumAS+=cardArrayS[i][j];
//                    }
//            }
        
        for (int[] eachRow : cardArrayS1) {
                        for (int j : eachRow) {
                                sumAS+=j;
                        }
//                        System.out.println("");
                }
         System.out.println("Cards to match: "+ sumAS);
         if(sumAS==0){
             imageClear1();
                System.out.println("Congrats! Game Completed");
                firstClick = true;
//                System.out.println("total time: "+min+"min. and "+sec%60+" sec.");
//                task.cancel(); // not cancel but reset timers only

                
            }
         
    }
    public void sumArrayS2(){ //checks the array value to know how many left to pair and if the game ends
        sumAS=0;
//        for(i = 0; i<cardInstances; i++)
//            {
//                for(j = 0; j<cardInstances; j++)
//                    {
//                        sumAS+=cardArrayS[i][j];
//                    }
//            }
        
        for (int[] eachRow : cardArrayS2) {
                        for (int j : eachRow) {
                                sumAS+=j;
                        }
//                        System.out.println("");
                }
         System.out.println("Cards to match: "+ sumAS);
         if(sumAS==0){
             imageClear1();
                System.out.println("Congrats! Game Completed");
                firstClick = true;
//                System.out.println("total time: "+min+"min. and "+sec%60+" sec.");
//                task.cancel(); // not cancel but reset timers only

                
            }
         
    }
         
    public void ArrayHCompare(){
        if(cardArrayH[x2][y2]==cardArrayH[x1][y1]){// compares 2 user inputed coord.
               //System.out.println("well done");
               cardArrayS[x2][y2]=0;
               cardArrayS[x1][y1]=0;
           } else{
               //System.out.println("WRONG"); count error
           }
            
            timer.schedule(new TimerTask(){ // Timer to para mag show ng saglet ung second card
                
                @Override
                public void run(){
                    imageClear();
                    notDone=false;
                    notDone2=false;
                }
            },500); 
            
    }
    public void ArrayHCompare1(){
        if(cardArrayH1[x2][y2]==cardArrayH1[x1][y1]){// compares 2 user inputed coord.
               //System.out.println("well done");
               cardArrayS1[x2][y2]=0;
               cardArrayS1[x1][y1]=0;
           } else{
               //System.out.println("WRONG"); count error
           }
            
            timer.schedule(new TimerTask(){ // Timer to para mag show ng saglet ung second card
                
                @Override
                public void run(){
                    imageClear1();
                    notDone=false;
                    notDone2=false;
                }
            },500); 
            
    }
    public void ArrayHCompare2(){
        if(cardArrayH2[x2][y2]==cardArrayH2[x1][y1]){// compares 2 user inputed coord.
               //System.out.println("well done");
               cardArrayS1[x2][y2]=0;
               cardArrayS1[x1][y1]=0;
           } else{
               //System.out.println("WRONG"); count error
           }
            
            timer.schedule(new TimerTask(){ // Timer to para mag show ng saglet ung second card
                
                @Override
                public void run(){
                    imageClear1();
                    notDone=false;
                    notDone2=false;
                }
            },500); 
            
    }
    
    public void imageClear(){

        switch(cardArrayS[0][0]){
            case 1:
                jButtonEasy00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonEasy00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;      
        }
        switch(cardArrayS[0][1]){
            case 1:
                jButtonEasy01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonEasy01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;      
        }
        
      
        switch(cardArrayS[1][0]){
            case 1:
                jButtonEasy10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonEasy10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        switch(cardArrayS[1][1]){
            case 1:
                jButtonEasy11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonEasy11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        
    }
    public void imageClear1(){

        switch(cardArrayS1[0][0]){
            case 1:
                jButtonEasyy00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonEasyy00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;      
        }
        switch(cardArrayS1[0][1]){
            case 1:
                jButtonEasyy01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonEasyy01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;      
        }
        
      
        switch(cardArrayS1[1][0]){
            case 1:
                jButtonEasyy10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonEasyy10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        switch(cardArrayS1[1][1]){
            case 1:
                jButtonEasyy11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonEasyy11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        switch(cardArrayS1[2][0]){
            case 1:
                jButtonEasyy20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonEasyy20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        switch(cardArrayS1[2][1]){
            case 1:
                jButtonEasyy21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonEasyy21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        
    }  
    public void imageClear2(){

        switch(cardArrayS2[0][0]){
            case 1:
                jButtonMedium00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;      
        }
        switch(cardArrayS2[0][1]){
            case 1:
                jButtonMedium01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;      
        }
        
      
        switch(cardArrayS2[1][0]){
            case 1:
                jButtonMedium10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        switch(cardArrayS2[1][1]){
            case 1:
                jButtonMedium11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        switch(cardArrayS2[2][0]){
            case 1:
                jButtonMedium20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        switch(cardArrayS2[2][1]){
            case 1:
                jButtonMedium21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
            switch(cardArrayS2[0][2]){
            case 1:
                jButtonMedium02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;      
        }
        switch(cardArrayS2[0][3]){
            case 1:
                jButtonMedium03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;      
        }
//        -------------------------
      
        switch(cardArrayS2[1][2]){
            case 1:
                jButtonMedium12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        switch(cardArrayS2[1][3]){
            case 1:
                jButtonMedium13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        switch(cardArrayS2[2][2]){
            case 1:
                jButtonMedium22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        switch(cardArrayS2[2][3]){
            case 1:
                jButtonMedium23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg")));
                break;
            case 0:
                jButtonMedium23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@solve.jpg")));
                break;     
        }
        
    }     
    public void buttonImageGiver(JButton a , int b){
        switch(b){
            case 1:
//                a.setIcon(imagea);
                a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/01.jpg")));
                break;
            case 2:
//                a.setIcon(imageb);
                a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/02.jpg")));
                break;
            case 3:
//                a.setIcon(imageb);
                a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/03.jpg")));
                break;
            case 4:
//                a.setIcon(imagea);
                a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/04.jpg")));
                break;
            case 5:
//                a.setIcon(imageb);
                a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/05.jpg")));
                break;
            case 6:
//                a.setIcon(imageb);
                a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/06.jpg")));
                break;
        }
    }
    public void firstClickRandomizer(){
        for (i=0;i<=cardInstances;i++){
                for(;;){                                    //first coordinate
                    x=(int)(Math.random()*2);
                    y=(int)(Math.random()*2);
                   if(cardArrayH[x][y]==0){
                       cardArrayH[x][y]=i;
                       break;
                   }else{
                       //System.out.println(x+" "+y);   
                   }
                }
                    for(;;){                                    //2nd coordinate but same value
                        x=(int)(Math.random()*2);
                        y=(int)(Math.random()*2);
                       if(cardArrayH[x][y]==0){
                           cardArrayH[x][y]=i;
                           break;
                       }else{
                           //System.out.println(x+" "+y);   
                       }
                    }
            }
        for(i=0;i<cardInstances;i++){
            for(j=0;j<cardInstances;j++){
                System.out.print(cardArrayH[i][j]+" ");
                }
            System.out.println(" ");
            }
         System.out.println(" ");
         for(i = 0; i<cardInstances; i++){
            for(j = 0; j<cardInstances; j++){
                cardArrayS [i][j]=1;
                System.out.print(cardArrayS[i][j]+" ");
                }
            System.out.println();
        }
        timer.scheduleAtFixedRate(task, 1000,1000); 
   
    }   
    public void firstClickRandomizer1(){
        for (i=0;i<=cardInstances1;i++){
                for(;;){                                    //first coordinate
                    x=(int)(Math.random()*3);
                    y=(int)(Math.random()*2);
                    
                   if(cardArrayH1[x][y]==0){
                       cardArrayH1[x][y]=i;
                       System.out.println(x+ " "+ y);
                       break;
                   }else{
                       //System.out.println(x+" "+y);   
                   }
                }
                    for(;;){                                    //2nd coordinate but same value
                        x=(int)(Math.random()*3);
                        y=(int)(Math.random()*2);
//                        System.out.println(x+ " "+ y);
                       if(cardArrayH1[x][y]==0){
                           cardArrayH1[x][y]=i;
                           System.out.println(x+ " "+ y);
                           break;
                       }else{
                           //System.out.println(x+" "+y);   
                       }
                    }
            }
        for(i=0;i<3;i++){
            for(j=0;j<2;j++){
                System.out.print(cardArrayH1[i][j]+" ");
                }
            System.out.println(" ");
            }
         System.out.println(" ");
//         for(i = 0; i<2; i++){
//            for(j = 0; j<3; j++){
//                cardArrayS [i][j]=1;
//                System.out.print(cardArrayS1[i][j]+" ");
//                }
//            System.out.println();
//        }
        
        for (int[] eachRow : cardArrayS1) {
                        for (int j : eachRow) {
                                
                                System.out.print(j + "\t");
                        }
                        System.out.println("");
                        
                }
        timer1.scheduleAtFixedRate(task1, 1000,1000); 
   
    }
    public void firstClickRandomizer2(){
        for (i=0;i<=cardInstances2;i++){
                for(;;){                                    //first coordinate
                    x=(int)(Math.random()*3);
                    y=(int)(Math.random()*4);
                    
                   if(cardArrayH2[x][y]==0){
                       cardArrayH2[x][y]=i;
//                       System.out.println(x+ " "+ y);
                       break;
                   }else{
                       //System.out.println(x+" "+y);   
                   }
                }
                    for(;;){                                    //2nd coordinate but same value
                        x=(int)(Math.random()*3);
                        y=(int)(Math.random()*4);
//                        System.out.println(x+ " "+ y);
                       if(cardArrayH2[x][y]==0){
                           cardArrayH2[x][y]=i;
//                           System.out.println(x+ " "+ y);
                           break;
                       }else{
                           //System.out.println(x+" "+y);   
                       }
                    }
            }
        for(i=0;i<3;i++){
            for(j=0;j<4;j++){
                System.out.print(cardArrayH2[i][j]+" ");
                }
            System.out.println(" ");
            }
         System.out.println(" ");
//         for(i = 0; i<2; i++){
//            for(j = 0; j<3; j++){
//                cardArrayS [i][j]=1;
//                System.out.print(cardArrayS1[i][j]+" ");
//                }
//            System.out.println();
//        }
        
        for (int[] eachRow : cardArrayS2) {
                        for (int j : eachRow) {
                                
                                System.out.print(j + "\t");
                        }
                        System.out.println("");
                        
                }
        timer1.scheduleAtFixedRate(task1, 1000,1000); 
   
    }
    TimerTask task = new TimerTask(){ // timer ng oras
        public void run(){
            System.out.println("timer");
//            sec++;
//            System.out.println("seconds"+ sec);
//            if(sec<=9){
//                secTimer.setText(String.valueOf("0"+sec%60));
//            }else{secTimer.setText(String.valueOf(sec%60));}
//            min= sec/60;
//            if(min<=9){
//                minTimer.setText(String.valueOf("0"+min));
//            }else{minTimer.setText(String.valueOf(min));}
            
        }
};
    TimerTask task1 = new TimerTask(){ // timer ng oras
        public void run(){
            System.out.println("timer");
//            sec++;
//            System.out.println("seconds"+ sec);
//            if(sec<=9){
//                secTimer.setText(String.valueOf("0"+sec%60));
//            }else{secTimer.setText(String.valueOf(sec%60));}
//            min= sec/60;
//            if(min<=9){
//                minTimer.setText(String.valueOf("0"+min));
//            }else{minTimer.setText(String.valueOf(min));}
            
        }
};
    TimerTask task2 = new TimerTask(){ // timer ng oras
        public void run(){
            System.out.println("timer");
//            sec++;
//            System.out.println("seconds"+ sec);
//            if(sec<=9){
//                secTimer.setText(String.valueOf("0"+sec%60));
//            }else{secTimer.setText(String.valueOf(sec%60));}
//            min= sec/60;
//            if(min<=9){
//                minTimer.setText(String.valueOf("0"+min));
//            }else{minTimer.setText(String.valueOf(min));}
            
        }
};
    
        
    private void jButtonEasy01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEasy01ActionPerformed
        // TODO add your handling code here:
        if(firstClick){
            firstClickRandomizer();
            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS[0][1]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==0 && y1==1){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;
            b =cardArrayH[0][1];     //***
            buttonImageGiver(jButtonEasy01, b);       //***
            x1=0;                                 //***
            y1=1;                                 //***
            System.out.println("1st choice");
        }else{
            
            notDone2= true;
            b =cardArrayH[0][1];     //***
            buttonImageGiver(jButtonEasy01, b);  //***
            x2=0;                                 //*** 
            y2=1;                                 //***  
            System.out.println("2nd choice");
                
            ArrayHCompare();
            sumArrayS();             
            clickCounter=1;
            }
    }//GEN-LAST:event_jButtonEasy01ActionPerformed

    private void jButtonEasy10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEasy10ActionPerformed
        // TODO add your handling code here:
        if(firstClick){
            firstClickRandomizer();
            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS[1][0]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==1 && y1==0){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;
            b =cardArrayH[1][0];     //***
            buttonImageGiver(jButtonEasy10, b);       //***
            x1=1;                                 //***
            y1=0;                                 //***
            System.out.println("1st choice");
        }else{
            
            notDone2= true;
            b =cardArrayH[1][0];     //***
            buttonImageGiver(jButtonEasy10, b);  //***
            x2=1;                                 //*** 
            y2=0;                                 //***  
            System.out.println("2nd choice");
                
            ArrayHCompare();
            sumArrayS();             
            clickCounter=1;
            }
    }//GEN-LAST:event_jButtonEasy10ActionPerformed

    private void jButtonEasy11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEasy11ActionPerformed
        // TODO add your handling code here:
        if(firstClick){
            firstClickRandomizer();
            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS[1][1]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==1 && y1==1){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;
            b =cardArrayH[1][1];     //***
            buttonImageGiver(jButtonEasy11, b);       //***
            x1=1;                                 //***
            y1=1;                                 //***
            System.out.println("1st choice");
        }else{
            
            notDone2= true;
            b =cardArrayH[1][1];     //***
            buttonImageGiver(jButtonEasy11, b);  //***
            x2=1;                                 //*** 
            y2=1;                                 //***  
            System.out.println("2nd choice");
                
            ArrayHCompare();
            sumArrayS();             
            clickCounter=1;
            }
    }//GEN-LAST:event_jButtonEasy11ActionPerformed

    private void jButtonEasyy10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEasyy10ActionPerformed
        // TODO add your handling code here:
        if(firstClick){
            
            firstClickRandomizer1();
            
            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS1[1][0]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==1 && y1==0){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;
            
            b =cardArrayH1[1][0];     //***
            buttonImageGiver(jButtonEasyy10, b);
            x1=1;                                 //***
            y1=0;                                 //***
            System.out.println("1st choice");
        }else{
            
            notDone2= true;
            
            
            b =cardArrayH1[1][0];     //***
            buttonImageGiver(jButtonEasyy10, b);
            x2=1;                                 //*** 
            y2=0;                                 //***  
            System.out.println("2nd choice");
                
            ArrayHCompare1();
            sumArrayS1();             
            clickCounter=1;
            }
   
    }//GEN-LAST:event_jButtonEasyy10ActionPerformed

    private void jButtonEasyy00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEasyy00ActionPerformed
        // TODO add your handling code here:
        if(firstClick){
            
            firstClickRandomizer1();
            
            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS1[0][0]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==0 && y1==0){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;
            
            b =cardArrayH1[0][0];     //***
            buttonImageGiver(jButtonEasyy00, b);
            x1=0;                                 //***
            y1=0;                                 //***
            System.out.println("1st choice");
        }else{
            
            notDone2= true;
            
            
            b =cardArrayH1[0][0];     //***
            buttonImageGiver(jButtonEasyy00, b);
            x2=0;                                 //*** 
            y2=0;                                 //***  
            System.out.println("2nd choice");
                
            ArrayHCompare1();
            sumArrayS1();             
            clickCounter=1;
            }
        
    }//GEN-LAST:event_jButtonEasyy00ActionPerformed

    private void jButtonEasyy01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEasyy01ActionPerformed
        // TODO add your handling code here:
        if(firstClick){
            
            firstClickRandomizer1();
            
            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS1[0][1]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==0 && y1==1){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;
            
            b =cardArrayH1[0][1];     //***
            buttonImageGiver(jButtonEasyy01, b);
            x1=0;                                 //***
            y1=1;                                 //***
            System.out.println("1st choice");
        }else{
            
            notDone2= true;
            
            
            b =cardArrayH1[0][1];     //***
            buttonImageGiver(jButtonEasyy01, b);
            x2=0;                                 //*** 
            y2=1;                                 //***  
            System.out.println("2nd choice");
                
            ArrayHCompare1();
            sumArrayS1();             
            clickCounter=1;
            }
   
    }//GEN-LAST:event_jButtonEasyy01ActionPerformed

    private void jButtonEasyy11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEasyy11ActionPerformed
        // TODO add your handling code here:
        if(firstClick){
            
            firstClickRandomizer1();
            
            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS1[1][1]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==1 && y1==1){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;
            
            b =cardArrayH1[1][1];     //***
            buttonImageGiver(jButtonEasyy11, b);
            x1=1;                                 //***
            y1=1;                                 //***
            System.out.println("1st choice");
        }else{
            
            notDone2= true;
            
            
            b =cardArrayH1[1][1];     //***
            buttonImageGiver(jButtonEasyy11, b);
            x2=1;                                 //*** 
            y2=1;                                 //***  
            System.out.println("2nd choice");
                
            ArrayHCompare1();
            sumArrayS1();             
            clickCounter=1;
            }
   
    }//GEN-LAST:event_jButtonEasyy11ActionPerformed

    private void jButtonEasyy20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEasyy20ActionPerformed
        // TODO add your handling code here:
        if(firstClick){
            
            firstClickRandomizer1();
            
            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS1[2][0]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==2 && y1==0){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;
            
            b =cardArrayH1[2][0];     //***
            buttonImageGiver(jButtonEasyy20, b);
            x1=2;                                 //***
            y1=0;                                 //***
            System.out.println("1st choice");
        }else{
            
            notDone2= true;
            
            
            b =cardArrayH1[2][0];     //***
            buttonImageGiver(jButtonEasyy20, b);
            x2=2;                                 //*** 
            y2=0;                                 //***  
            System.out.println("2nd choice");
                
            ArrayHCompare1();
            sumArrayS1();             
            clickCounter=1;
            }
   
    }//GEN-LAST:event_jButtonEasyy20ActionPerformed

    private void jButtonEasyy21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEasyy21ActionPerformed
        // TODO add your handling code here:
        if(firstClick){
            
            firstClickRandomizer1();
            
            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS1[2][1]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==2 && y1==1){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;
            
            b =cardArrayH1[2][1];     //***
            buttonImageGiver(jButtonEasyy21, b);
            x1=2;                                 //***
            y1=1;                                 //***
            System.out.println("1st choice");
        }else{
            
            notDone2= true;
            
            
            b =cardArrayH1[2][1];     //***
            buttonImageGiver(jButtonEasyy21, b);
            x2=2;                                 //*** 
            y2=1;                                 //***  
            System.out.println("2nd choice");
                
            ArrayHCompare1();
            sumArrayS1();             
            clickCounter=1;
            }
   
    }//GEN-LAST:event_jButtonEasyy21ActionPerformed

    private void jButtonMedium00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium00ActionPerformed
        // TODO add your handling code here:
        if(firstClick){
            
            firstClickRandomizer2();
            
            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[0][0]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==0 && y1==0){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;
            
            b =cardArrayH2[0][0];     //***
            buttonImageGiver(jButtonEasyy00, b);//***
            x1=0;                                 //***
            y1=0;                                 //***
            System.out.println("1st choice");
        }else{
            
            notDone2= true;
            
            
            b =cardArrayH2[0][0];     //***
            buttonImageGiver(jButtonEasyy00, b);//***
            x2=0;                                 //*** 
            y2=0;                                 //***  
            System.out.println("2nd choice");
                
            ArrayHCompare2();
            sumArrayS2();             
            clickCounter=1;
            }
    
    }//GEN-LAST:event_jButtonMedium00ActionPerformed

    private void jButtonMedium10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium10ActionPerformed

    private void jButtonMedium01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium01ActionPerformed

    private void jButtonMedium11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium11ActionPerformed

    private void jButtonMedium21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium21ActionPerformed

    private void jButtonMedium20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium20ActionPerformed

    private void jButtonMedium02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium02ActionPerformed

    private void jButtonMedium12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium12ActionPerformed

    private void jButtonMedium22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium22ActionPerformed

    private void jButtonMedium03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium03ActionPerformed

    private void jButtonMedium13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium13ActionPerformed

    private void jButtonMedium23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new mainFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gamePanel1;
    private javax.swing.JPanel gamePanel2;
    private javax.swing.JPanel gamePanel3;
    private javax.swing.JPanel gamePanel4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonEasy00;
    private javax.swing.JButton jButtonEasy01;
    private javax.swing.JButton jButtonEasy10;
    private javax.swing.JButton jButtonEasy11;
    private javax.swing.JButton jButtonEasyy00;
    private javax.swing.JButton jButtonEasyy01;
    private javax.swing.JButton jButtonEasyy10;
    private javax.swing.JButton jButtonEasyy11;
    private javax.swing.JButton jButtonEasyy20;
    private javax.swing.JButton jButtonEasyy21;
    private javax.swing.JButton jButtonMedium00;
    private javax.swing.JButton jButtonMedium01;
    private javax.swing.JButton jButtonMedium02;
    private javax.swing.JButton jButtonMedium03;
    private javax.swing.JButton jButtonMedium10;
    private javax.swing.JButton jButtonMedium11;
    private javax.swing.JButton jButtonMedium12;
    private javax.swing.JButton jButtonMedium13;
    private javax.swing.JButton jButtonMedium20;
    private javax.swing.JButton jButtonMedium21;
    private javax.swing.JButton jButtonMedium22;
    private javax.swing.JButton jButtonMedium23;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
