/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

/**
 *
 * @author engeer
 */
public class o_gamePanel4 extends javax.swing.JPanel {

    /**
     * Creates new form o_gamePanel4
     */
    public o_gamePanel4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMedium00 = new javax.swing.JButton();
        jButtonMedium01 = new javax.swing.JButton();
        jButtonMedium02 = new javax.swing.JButton();
        jButtonMedium03 = new javax.swing.JButton();
        jButtonMedium13 = new javax.swing.JButton();
        jButtonMedium12 = new javax.swing.JButton();
        jButtonMedium11 = new javax.swing.JButton();
        jButtonMedium10 = new javax.swing.JButton();
        jButtonMedium20 = new javax.swing.JButton();
        jButtonMedium21 = new javax.swing.JButton();
        jButtonMedium22 = new javax.swing.JButton();
        jButtonMedium23 = new javax.swing.JButton();
        jButtonMedium30 = new javax.swing.JButton();
        jButtonMedium31 = new javax.swing.JButton();
        jButtonMedium32 = new javax.swing.JButton();
        jButtonMedium33 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 255));
        setPreferredSize(new java.awt.Dimension(669, 623));

        jButtonMedium00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium00.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium00.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium00.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium00.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium00ActionPerformed(evt);
            }
        });

        jButtonMedium01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium01.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium01.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium01.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium01.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium01ActionPerformed(evt);
            }
        });

        jButtonMedium02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium02.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium02.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium02.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium02.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium02ActionPerformed(evt);
            }
        });

        jButtonMedium03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium03.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium03.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium03.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium03.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium03ActionPerformed(evt);
            }
        });

        jButtonMedium13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium13.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium13.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium13.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium13ActionPerformed(evt);
            }
        });

        jButtonMedium12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium12.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium12.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium12.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium12ActionPerformed(evt);
            }
        });

        jButtonMedium11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium11.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium11.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium11.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium11ActionPerformed(evt);
            }
        });

        jButtonMedium10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium10.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium10.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium10.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium10ActionPerformed(evt);
            }
        });

        jButtonMedium20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium20.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium20.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium20.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium20.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium20ActionPerformed(evt);
            }
        });

        jButtonMedium21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium21.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium21.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium21.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium21.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium21ActionPerformed(evt);
            }
        });

        jButtonMedium22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium22.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium22.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium22.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium22.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium22ActionPerformed(evt);
            }
        });

        jButtonMedium23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium23.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium23.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium23.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium23.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium23ActionPerformed(evt);
            }
        });

        jButtonMedium30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium30.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium30.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium30.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium30.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium30ActionPerformed(evt);
            }
        });

        jButtonMedium31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium31.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium31.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium31.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium31.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium31ActionPerformed(evt);
            }
        });

        jButtonMedium32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium32.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium32.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium32.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium32.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium32ActionPerformed(evt);
            }
        });

        jButtonMedium33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/@back.jpg"))); // NOI18N
        jButtonMedium33.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMedium33.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonMedium33.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonMedium33.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonMedium33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedium33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMedium30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonMedium20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMedium21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonMedium10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonMedium11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonMedium00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonMedium01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMedium22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonMedium12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonMedium02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMedium23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonMedium13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonMedium03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMedium03, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMedium02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMedium22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonMedium01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMedium00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonMedium11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMedium10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMedium20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMedium21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMedium33, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMedium32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMedium30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMedium31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMedium00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium00ActionPerformed
        // TODO add your handling code here:
        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[0][0]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==0 && y1==0){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[0][0];     //***
            buttonImageGiver(jButtonMedium00, b);//***
            x1=0;                                 //***
            y1=0;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[0][0];     //***
            buttonImageGiver(jButtonMedium00, b);//***
            x2=0;                                 //***
            y2=0;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium00ActionPerformed

    private void jButtonMedium01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium01ActionPerformed
        // TODO add your handling code here:

        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[0][1]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==0 && y1==1){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[0][1];     //***
            buttonImageGiver(jButtonMedium01, b);//***
            x1=0;                                 //***
            y1=1;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[0][1];     //***
            buttonImageGiver(jButtonMedium01, b);//***
            x2=0;                                 //***
            y2=1;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium01ActionPerformed

    private void jButtonMedium02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium02ActionPerformed
        // TODO add your handling code here:
        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[0][2]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==0 && y1==2){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[0][2];     //***
            buttonImageGiver(jButtonMedium02, b);//***
            x1=0;                                 //***
            y1=2;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[0][2];     //***
            buttonImageGiver(jButtonMedium02, b);//***
            x2=0;                                 //***
            y2=2;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium02ActionPerformed

    private void jButtonMedium03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium03ActionPerformed
        // TODO add your handling code here:

        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[0][3]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==0 && y1==3){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[0][3];     //***
            buttonImageGiver(jButtonMedium03, b);//***
            x1=0;                                 //***
            y1=3;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[0][3];     //***
            buttonImageGiver(jButtonMedium03, b);//***
            x2=0;                                 //***
            y2=3;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium03ActionPerformed

    private void jButtonMedium13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium13ActionPerformed
        // TODO add your handling code here:

        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[1][3]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==1 && y1==3){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[1][3];     //***
            buttonImageGiver(jButtonMedium13, b);//***
            x1=3;                                 //***
            y1=3;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[1][3];     //***
            buttonImageGiver(jButtonMedium13, b);//***
            x2=1;                                 //***
            y2=3;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium13ActionPerformed

    private void jButtonMedium12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium12ActionPerformed
        // TODO add your handling code here:
        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[1][2]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==1 && y1==2){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[1][2];     //***
            buttonImageGiver(jButtonMedium12, b);//***
            x1=1;                                 //***
            y1=2;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[1][2];     //***
            buttonImageGiver(jButtonMedium12, b);//***
            x2=1;                                 //***
            y2=2;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium12ActionPerformed

    private void jButtonMedium11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium11ActionPerformed
        // TODO add your handling code here:

        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[1][1]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==1 && y1==1){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[1][1];     //***
            buttonImageGiver(jButtonMedium11, b);//***
            x1=1;                                 //***
            y1=1;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[1][1];     //***
            buttonImageGiver(jButtonMedium11, b);//***
            x2=1;                                 //***
            y2=1;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium11ActionPerformed

    private void jButtonMedium10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium10ActionPerformed
        // TODO add your handling code here:
        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[1][0]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==1 && y1==0){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[1][0];     //***
            buttonImageGiver(jButtonMedium10, b);//***
            x1=1;                                 //***
            y1=0;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[1][0];     //***
            buttonImageGiver(jButtonMedium10, b);//***
            x2=1;                                 //***
            y2=0;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium10ActionPerformed

    private void jButtonMedium20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium20ActionPerformed
        // TODO add your handling code here:
        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[2][0]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==2 && y1==0){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[2][0];     //***
            buttonImageGiver(jButtonMedium20, b);//***
            x1=2;                                 //***
            y1=0;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[2][0];     //***
            buttonImageGiver(jButtonMedium20, b);//***
            x2=2;                                 //***
            y2=0;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium20ActionPerformed

    private void jButtonMedium21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium21ActionPerformed
        // TODO add your handling code here:
        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[2][1]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==2 && y1==1){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[2][1];     //***
            buttonImageGiver(jButtonMedium21, b);//***
            x1=2;                                 //***
            y1=1;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[2][1];     //***
            buttonImageGiver(jButtonMedium21, b);//***
            x2=2;                                 //***
            y2=1;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium21ActionPerformed

    private void jButtonMedium22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium22ActionPerformed
        // TODO add your handling code here:

        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[2][2]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==2 && y1==2){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[2][2];     //***
            buttonImageGiver(jButtonMedium22, b);//***
            x1=2;                                 //***
            y1=2;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[2][2];     //***
            buttonImageGiver(jButtonMedium22, b);//***
            x2=2;                                 //***
            y2=2;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium22ActionPerformed

    private void jButtonMedium23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium23ActionPerformed
        // TODO add your handling code here:

        if(firstClick){

            firstClickRandomizer2();

            //System.out.println("check check22");
            firstClick = false;
        }
        if(cardArrayS2[2][3]==0 ){                 //***
            System.out.println("this card is already done"); // error counting ?
        }else if(x1==2 && y1==3){                 //***
            System.out.println("this is your 1st choice pick another card"); // error counting ?
        }else if(notDone==true && notDone2==true){                           //prevent actions while pairing
            System.out.println("di pa tpos mag compute sandali naman");
        }else if(clickCounter==1){
            notDone= true;
            clickCounter=2;

            b =cardArrayH2[2][3];     //***
            buttonImageGiver(jButtonMedium23, b);//***
            x1=2;                                 //***
            y1=3;                                 //***
            System.out.println("1st choice");
        }else{

            notDone2= true;

            b =cardArrayH2[2][3];     //***
            buttonImageGiver(jButtonMedium23, b);//***
            x2=2;                                 //***
            y2=3;                                 //***
            System.out.println("2nd choice");

            ArrayHCompare2();
            sumArrayS2();
            clickCounter=1;
        }

    }//GEN-LAST:event_jButtonMedium23ActionPerformed

    private void jButtonMedium30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium30ActionPerformed

    private void jButtonMedium31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium31ActionPerformed

    private void jButtonMedium32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium32ActionPerformed

    private void jButtonMedium33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedium33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedium33ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMedium00;
    private javax.swing.JButton jButtonMedium01;
    private javax.swing.JButton jButtonMedium02;
    private javax.swing.JButton jButtonMedium03;
    private javax.swing.JButton jButtonMedium10;
    private javax.swing.JButton jButtonMedium11;
    private javax.swing.JButton jButtonMedium12;
    private javax.swing.JButton jButtonMedium13;
    private javax.swing.JButton jButtonMedium20;
    private javax.swing.JButton jButtonMedium21;
    private javax.swing.JButton jButtonMedium22;
    private javax.swing.JButton jButtonMedium23;
    private javax.swing.JButton jButtonMedium30;
    private javax.swing.JButton jButtonMedium31;
    private javax.swing.JButton jButtonMedium32;
    private javax.swing.JButton jButtonMedium33;
    // End of variables declaration//GEN-END:variables
}
